# Site settings
baseURL = "https://tommarekbrno.github.io/datavizmeetup/"
languageCode = "en-US"
title = "data+vis meetup #brno"
theme = "hugo-split-theme"
disableKinds = ["section", "taxonomy", "taxonomyTerm", "RSS", "sitemap"]
publishDir = "docs"

# Local preview mode
relativeURLs = true
uglyURLs = true

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Copyright
copyright = "&copy;2022 datavizmeetup"


[params]

  # Metadata for search engines and social sharing
  author = "data+vis meetup"
  description = "Povídáme si o datech, jejich vizualizaci a komunikaci. Jednou za dva měsíce, v Brně."
  shareImage = "images/social.jpg"
  twitterHandle = "onepagelove"

  # Favicon
  favicon = "favicon.ico"

  [params.custom.css]
  enable = true

  # Section - Visual
  [params.visual]

    # Image
    [params.visual.image]
      enable = true
      file = "images/background3.jpg"
      position = "center center"

    # Video
    [params.visual.video]
      enable = false
      mute = true
      file = "videos/background.mp4"
      # youtubeId = "dk9uNWPP7EA"

  # Links
  #
  # Links List #1
  [[params.links]]
    [params.links.list1]
      heading = "Přidejte se"

      [[params.links.list1.link]]
        text = "Program meetupu"
        url = "/program"

      [[params.links.list1.link]]
        text = "Google skupina"
        url = "#"

      [[params.links.list1.link]]
        text = "WhatsApp skupina"
        url = "#"

  # Links List #2
  [[params.links]]
    [params.links.list2]
      heading = "Archiv"

      [[params.links.list2.link]]
        text = "Zápisy setkání"
        url = "#"




  # The original template is released under the Creative Commons Attribution 3.0 License.
  # Please keep the original attribution link when using for your own project.
  # If you'd like to use the template without the attribution, you can check out
  # the license option via the template author's website: https://onepagelove.com/split